const {Schema, model} = require('mongoose')

const schema = new Schema({
	uid: {type: String, required: true},
	name: {type: String, required: true},
	nation: {type: String},
	ca: {type: Number},
	pa: {type: Number},
	age: {type: Number},
	position: {type: String},
	height: {type: String},
	weight: {type: String},
	cr: {type: Number},
	preferredfoot: {type: String},
	mins: {type: Number},
	avrat: {type: Number},
	price: {type: Number},
	club: {type: String},
	lth: {type: String},
	lon: {type: String},
	dri: {type: String},
	fin: {type: String},
	hea: {type: String},
	fre: {type: String},
	cro: {type: String},
	mar: {type: String},
	tck: {type: String},
	pas: {type: Number},
	pen: {type: String},
	fir: {type: String},
	tec: {type: String},
	cor: {type: String},
	agg: {type: String},
	vis: {type: String},
	pos: {type: String},
	otb: {type: String},
	fla: {type: String},
	ant: {type: String},
	tea: {type: String},
	cnt: {type: String},
	ldr: {type: String},
	dec: {type: String},
	wor: {type: String},
	det: {type: String},
	cmp: {type: String},
	bra: {type: String},
	sta: {type: String},
	jum: {type: String},
	bal: {type: String},
	agi: {type: String},
	nat: {type: String},
	str: {type: String},
	pac: {type: String},
	acc: {type: String},
	amb: {type: String},
	impm: {type: String},
	prof: {type: String},
	injpr: {type: String},
	cons: {type: String},
	thr: {type: String},
	com: {type: String},
	kic: {type: String},
	cmd: {type: String},
	tro: {type: String},
	han: {type: String},
	ovo: {type: String},
	pun: {type: String},
	pasgk: {type: String},
	firgk: {type: String},
	ref: {type: String},
	aer: {type: String},
	ecc: {type: String}
})

module.exports = model('Squadlist', schema)